import { safeLinks } from "./safelinks";
import { addTabs } from "./tabs";
import "./active";
import "./collapsible-nav";
import "./copy";
import "./dark";
import "./menu";
import "./prism.js";
import "./safelinks";
import { showToast } from "./toast";
import "./wrapTables";
window["showToast"] = showToast;
